# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c4d431b45107ad906ff9ee4a8ccec24858a34cdbd9366819c7f9e88b280b96b9b327324569f838c79f03188fe9c5769f11691da35a30ce3eb21f7199510a508

test:
  secret_key_base: 3d2a0321afeb78f5dcb001ee89e71c33b3f9e68654d0d63f6ccae3b9573925e9f022dc7f7553f6be0abd875a37f25b46afb67481d83a2474adddeeba59e41111

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
